import cv2
import numpy as np
import matplotlib.pyplot as plt
def show_comparison(Original,sobel,prewitt,canny):
  plt.figure(figsize=(12,10))
  plt.subplot(2,2,1)
  plt.imshow(Original,cmap='gray')
  plt.title("Original Grayscale Image")
  plt.axis('off')
  plt.subplot(2,2,2)
  plt.imshow(sobel,cmap='gray')
  plt.title("Sobel Edge Detection")
  plt.axis('off')
  plt.subplot(2,2,3)
  plt.imshow(prewitt,cmap='gray')
  plt.title("Prewitt Edge Detection")
  plt.axis('off')
  plt.subplot(2,2,4)
  plt.imshow(canny,cmap='gray')
  plt.title("Canny Edge Detection")
  plt.axis('off')
  plt.tight_layout()
  plt.show()
img=cv2.imread('sunflower.jpg',0) 
if img is None:
    print("Error: Image not found.")
else:
    sobelx=cv2.Sobel(img,cv2.CV_64F,1,0,ksize=3)
    sobely=cv2.Sobel(img,cv2.CV_64F,0,1,ksize=3)
    sobel_combined=cv2.magnitude(sobelx,sobely)
    sobel_result=np.uint8(np.absolute(sobel_combined))
    kernelx=np.array([[1,1,1],[0,0,0],[-1,-1,-1]])
    kernely=np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
    prewittx=cv2.filter2D(img,-1,kernelx)
    prewitty=cv2.filter2D(img,-1,kernely)
    prewitt_combined=prewittx+ prewitty
    prewitt_result=cv2.convertScaleAbs(prewitt_combined)
    canny_edges=cv2.Canny(img,100,200)
    cv2.imwrite('original_grayscale.jpg',img)
    cv2.imwrite('sobel_output.jpg',sobel_result)
    cv2.imwrite('prewitt_output.jpg',prewitt_result)
    cv2.imwrite('canny_output.jpg',canny_edges)
    show_comparison(img,sobel_result,prewitt_result,canny_edges) 
    print("1.original_grayscale.jpg")
    print("2.sobel_output.jpg")
    print("3.prewitt_output.jpg")
    print("4.canny_output.jpg")
